[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
description = "Proteus is intended to make dynamic transformation of data using serde serializable, deserialize using JSON and a JSON transformation syntax similar to Javascript JSON syntax."
edition = "2018"
keywords = [
    "json",
    "transform",
    "transformation",
]
license = "MIT OR Apache-2.0"
name = "proteus"
readme = "README.md"
version = "0.1.0"

[badges.travis-ci]
repository = "rust-playground/proteus"

[[bench]]
harness = false
name = "bench"

[dependencies]
lazy_static = "1.4.0"
regex = "1.3.1"
serde_json = "1.0.44"
snafu = "0.6.0"
typetag = "0.1.4"

[dependencies.serde]
features = ["derive"]
version = "1.0.104"

[dev-dependencies]
criterion = "0.3.0"

[lib]
bench = false
